### PR TITLE
Add action to build tiles from input

### PR DESCRIPTION
**Pull request by luandro**
## Goal
Add ability to build tiles from inputs in Actions tab in Github.

### CODE REVIEW

**Comment by rudokemper** [comment]
Hey @luandro can you describe a bit more the intended use case for this?

**Comment by luandro** [comment]
Might not be very relevant once the UI is working. It's just a way to build tiles from the Action tab, without having to use the manifest like in the template, in case somebody forks for example and wants to build without touching code.

image

**Comment by rudokemper** [comment]
That's fine, I think this repo can support different use cases (CLI, web app, build pipelines). Could you add to the documentation in the readme, though? That way others can know about this possibility.

**Comment by rudokemper** [comment]
@luandro I made a few changes to be consistent in the usage of flag names (and when they are optional or not), and to add a couple of new flags that were introduced (tiletype, ratio, openstreetmap). The most impactful change is that I made `filename` (formerly `tile_name`) optional in the build script, since there is already a default fallback value provided for that in the code. 
Let me know if you agree with my changes.

**Comment by luandro** [comment]
There's a max of 10 input fields. Would have to remove one (if i'm counting it right).

**Comment by rudokemper** [comment]
Ah, I see. Then I'd remove tiletype and radio.

**Comment by luandro** [comment]
Looking good now!

**Pull request merged**
